name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' # Điều chỉnh phiên bản PHP nếu cần
        extensions: mbstring, xml, bcmath, sqlite3, gd

    - name: Change to project directory
      run: cd noithat_laravel

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --verbose

    - name: Run Tests
      run: php artisan test
