name: Reviewdog CI for PHP_CodeSniffer

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Đặt phiên bản PHP phù hợp với dự án

      - name: Install dependencies
        run: composer install

      - name: PHP_CodeSniffer with Reviewdog
        uses: reviewdog/action-phpcs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          phpcs_flags: "--standard=PSR12"  # Tiêu chuẩn kiểm tra code PSR12
          level: "error"  # Chỉ review các lỗi nghiêm trọng
