name: Reviewdog CI

on:
  pull_request:
    paths:
      - '**/*.php'  # Chỉ chạy linter trên các file PHP.
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Đặt phiên bản PHP phù hợp với dự án của bạn.

      - name: Install dependencies
        run: composer install  # Sử dụng Composer để cài đặt phụ thuộc.

      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"

      - name: Run PHP_CodeSniffer with Reviewdog
        uses: reviewdog/action-phpcs@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Đưa ra review trong pull request
          phpcs_flags: '--standard=PSR2 ./' # Chạy PHP_CodeSniffer với chuẩn PSR2.
