name: PHP CodeSniffer with Reviewdog

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install PHP and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install php-cli php-xml
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      - name: Install PHP_CodeSniffer
        run: |
          php composer.phar global require squizlabs/php_codesniffer

      - name: Run PHP_CodeSniffer
        run: |
          ~/.composer/vendor/bin/phpcs --standard=PSR12 app/ --report=full | reviewdog -f=phpcs -reporter=github-pr-review -level=error

      - name: Reviewdog
        uses: reviewdog/reviewdog@latest # Hoặc sử dụng tag cụ thể như `v1.22.0`
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
